name: Conditional sync to ParaTranz in parallel

on:
  workflow_call:
  workflow_dispatch:

jobs:
  zh_CN:
    uses: ./.github/workflows/conditional-sync-to-paratranz.yml
    with:
      target_lang: zh_CN
    secrets: inherit