name: Entrypoint for nightly workflows

on:
  schedule:
    - cron: "30 1 * * *" # 1:30am UTC every day, before modpack nightly builds
  workflow_dispatch:

jobs:
  save-nightly-modpack-history:
    uses: ./.github/workflows/save-nightly-modpack-history.yml
  conditional-sync-to-paratranz-parallel:
    needs: save-nightly-modpack-history
    uses: ./.github/workflows/conditional-sync-to-paratranz-parallel.yml
    secrets: inherit
  publish-all-nightly-lang-packs:
    needs: conditional-sync-to-paratranz-parallel
    uses: ./.github/workflows/publish-all-nightly-lang-packs.yml
    secrets: inherit
