name: Publish all daily lang packs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  zh_CN:
    uses: ./.github/workflows/publish-daily-lang-pack.yml
    with:
      target_lang: zh_CN
    secrets: inherit
