name: Publish all nightly lang packs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  zh_CN:
    uses: ./.github/workflows/publish-nightly-lang-pack.yml
    with:
      target_lang: zh_CN
    secrets: inherit
