name: Save nightly modpack history

on:
  workflow_call:
  workflow_dispatch:

jobs:
  save-nightly-modpack-history:
    name: Save nightly modpack history
    runs-on: ubuntu-latest
    steps:
      - name: Checkout miozune/GTNH-translation-compare
        uses: actions/checkout@v4
        with:
          repository: miozune/GTNH-translation-compare
          ref: main
      - name: Ensure Dependencies
        uses: ./.github/actions/ensure-dependencies

      - name: Fetch artifact ID
        id: fetch-artifact-id
        shell: bash
        run: |
          echo "artifact_id=$(gh --repo GTNewHorizons/DreamAssemblerXXL run list \
            --limit 1 --workflow "Nightly modpack build" --json databaseId --jq '.[].databaseId')" \
            >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout nightly-history branch
        uses: actions/checkout@v4
        with:
          ref: nightly-history
          path: nightly-repo
      - name: Ensure .nightly-temp
        shell: bash
        run:
          mkdir .nightly-temp
      - name: Download nightly
        shell: bash
        working-directory: .nightly-temp
        run: |
          gh --repo GTNewHorizons/DreamAssemblerXXL run download \
            ${{ steps.fetch-artifact-id.outputs.artifact_id }} \
            --pattern *-mmcprism-new-java
          # gh automatically unzips the first layer of the zip, one more zip left
          cd $(ls | head -1)
          unzip -o $(ls | head -1) -d ../unzip-tmp
          cd ..
          mv "unzip-tmp/GT New Horizons nightly" nightly
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save nightly modpack history
        run: >-
          poetry run python main.py action save-nightly-modpack-history
          --modpack-path='.nightly-temp/nightly' --repo-path='nightly-repo'
        env:
          # Required by system validation but actually unused
          PARATRANZ_TOKEN: -1
          PARATRANZ_PROJECT_ID: -1
          TARGET_LANG: "en_US"
      - name: Push commit
        working-directory: nightly-repo
        run:
          git push origin nightly-history
